server:
  port: 9001
  servlet:
    context-path: /
  tomcat:
    accesslog:
      enabled: true

logging:
  level:
    ROOT: INFO
    az.company.card: DEBUG
#    org.mongodb.driver: DEBUG

application:
  swagger:
    base-package: "az.company.card.adapter.in"
    paths: "/.*"
    apiInfo:
      version: 1.0
      title: "Card REST API"
      description: "Spring Boot REST API for Card"
      termsOfServiceUrl:
      license: "Apache License Version 2.0"
      licenseUrl: "https://www.apache.org/licenses/LICENSE-2.0"
      contact:
        name: "Elchin Gasimov, LinkedIn: /in/egasimov"
        url: "https://YOUR_ADDRESS/"
        email: "egasimov0@gmail.com"


spring:
  data:
    mongodb:
      database: CardDB
      host: localhost
      port: 27017


app:
  clients:
    event-service:
      url: http://localhost:9004
  kafka:
    bootstrap-servers: localhost:9092
    application-id-config: ms-card
    transaction-id-prefix: tnx-01
    idempotence: true
    acks: all
    topic:
      card-order-storage: topic-card-order-storage
      card-order-processing: topic-card-order-processing



